// GENERATED FILE - DO NOT EDIT
//
// This file was generated by applying the following macros to the
// `example/observable.gen.dart` file:
//
//
// To make changes you should edit the `example/observable.gen.dart` file;

import 'macros/observable.dart';

class ObservableThing {
  @observable
  String _description;
  ObservableThing(this._description);
}
