// GENERATED FILE - DO NOT EDIT
//
// This file was generated by applying the following macros to the
// `example/shape.gen.dart` file:
//
//
// To make changes you should edit the `example/shape.gen.dart` file;

import 'macros/data_class.dart';
import 'macros/freezed.dart';
import 'macros/json.dart';

@freezed
abstract class Shape {
  void prettyPrint() {
    when(
        circle: (radius, _) => print('when $debugLabel: Circle radius $radius'),
        rectangle: (width, height, _) =>
            print('when $debugLabel: Rectangle width $width height $height'));
  }

  factory Shape.circle(double radius, {String? debugLabel}) = ShapeCircle;
  factory Shape.rectangle(
      {required double width,
      required double height,
      String? debugLabel}) = ShapeRectangle;
}
