// GENERATED FILE - DO NOT EDIT
//
// This file was generated by applying the following macros to the
// `example/shape.gen.dart` file:
//
//
// To make changes you should edit the `example/shape.gen.dart` file;

import 'macros/freezed.dart';

@freezed
abstract class Shape {
  String toPrettyString() {
    return when(
        circle: (radius, _) => 'when $debugLabel: Circle radius $radius',
        rectangle: (width, height, _) =>
            'when $debugLabel: Rectangle width $width height $height');
  }

  factory Shape.circle(double radius, {String? debugLabel}) = ShapeCircle;
  factory Shape.rectangle(
      {required double width,
      required double height,
      String? debugLabel}) = ShapeRectangle;
}
