name: isolate_experiments
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  macro_builder:
    path: ../
dev_dependencies:
  analyzer: ^2.0.0
  async: ^2.8.2
  graphs: ^2.1.0
  package_config: ^2.0.2
  path: ^1.8.0
  pub_semver: ^2.1.0
  vm_service: ^7.3.0
